- hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Docker dependencies
      apt:
        name:
          - docker.io
          - python3-pip
        state: present
    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present
        executable: pip3
    - name: Check Docker version
      command: docker --version
      register: docker_version_output
    - debug:
        msg: "Docker version is {{ docker_version_output.stdout }}"