name: Terraform Apply

on:
    push:
        branches:
            - Dev
    pull_request:
        branches:
            - main

jobs:
    terraform:
        runs-on: ubuntu-latest

        steps:
            - name: Check repository
              uses: actions/checkout@v4

            - name: Set up AWS CLI
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.ACCESS_KEY}}
                  aws-secret-access-key: ${{ secrets.SECRET_KEY}}
                  aws-region: ${{ secrets.REGION}}

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.9.1

            - name: Terraform Init
              working-directory: ./Terraform
              run: terraform init

            - name: Terraform Apply
              working-directory: ./Terraform
              run: terraform apply -auto-approve 
              #env:
                #AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY}}
                #AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY}}